### ISSUE TITLE
Uncaught TypeError: state.onionForm.getIn is not a function

### ISSUE THREAD

**Issue by joeyfigaro** [blueberryapps/onion-form#5]
Looks like onion-form requires state objects to be of type `Map` - if I remove the middleware I have in place for translating immutable -> js, it works fine. What do you think of adding a check for `setIn` prior to using it?

**Comment by ondrejbartas** [comment]
Onion form require you to pass reducer to combineReducers under `onionForm` key
```
import { reducer as onionForm } form 'onion-form'
createStore(combineReducers({
  onionForm
}))
```

**Comment by joeyfigaro** [comment]
@ondrejbartas Did that. :) The error I'm getting is over onionForm's state object not being immutable. It's not immutable because some middleware I have is translating immutable objects to regular objects. 

The middleware might allow me to skip over keys... I'll check into that.
