### ISSUE TITLE
Unknown props in <input>

### ISSUE THREAD

**Issue by joeyfigaro** [blueberryapps/onion-form#6]
**error**
```
Warning: Unknown props `onionFieldRegister`, `onionLiveValidate`, `onionOnSubmit`, `field`, `actions`, `error`, `hint`, `onionFormName`, `tooltip` on <input> tag.
```

Attempting to run the example and a form of my own and receiving this error. 

[More about this in the docs](https://facebook.github.io/react/warnings/unknown-prop.html)

**Comment by ondrejbartas** [comment]
Hi, this is because `connectField()` decorator is passing additional props to decorated component.

Best approach is to cherry pick props you will need in your input component.
